export const STICKY_NOTE_START = "STICKY_NOTE_START";
export const STICKY_NOTE_SUCCESS = "STICKY_NOTE_SUCCESS";
export const STICKY_NOTE_FAIL = "STICKY_NOTE_FAIL";

export const STICKY_NOTE_DEL_START = "STICKY_NOTE_DEL_START";
export const STICKY_NOTE_DEL_SUCCESS = "STICKY_NOTE_DEL_SUCCESS";
export const STICKY_NOTE_DEL_FAIL = "STICKY_NOTE_DEL_FAIL";

export const CREATE_STICKY_NOTE_START = "CREATE_STICKY_NOTE_START";
export const CREATE_STICKY_NOTE_SUCCESS = "CREATE_STICKY_NOTE_SUCCESS";
export const CREATE_STICKY_NOTE_FAIL = "CREATE_STICKY_NOTE_FAIL";

export const UPDATE_STICKY_NOTE_START = "UPDATE_STICKY_NOTE_START";
export const UPDATE_STICKY_NOTE_SUCCESS = "UPDATE_STICKY_NOTE_SUCCESS";
export const UPDATE_STICKY_NOTE_FAIL = "UPDATE_STICKY_NOTE_FAIL";
